"""empty message

Revision ID: 40f6fe372e08
Revises: 966a30eec8c3
Create Date: 2022-10-17 12:58:27.406273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f6fe372e08'
down_revision = '966a30eec8c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
