"""empty message

Revision ID: 966a30eec8c3
Revises: 749f7c5b014d
Create Date: 2022-10-17 12:49:57.028970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966a30eec8c3'
down_revision = '749f7c5b014d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('associoation',
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['Goods.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tags_id', 'goods_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associoation')
    op.drop_table('tags')
    # ### end Alembic commands ###
